-- Pet Supplies Database

-- 1.
SELECT FIRST_NAME, LAST_NAME
 FROM CUSTOMER
WHERE CREDIT_LIMIT > 500;

--2.
SELECT INVOICE_NUM
 FROM INVOICES
WHERE CUST_ID = 435 
 AND INVOICE_DATE = '2021-11-18';

--3.
SELECT ITEM_ID, DESCRIPTION
 FROM ITEM
WHERE CATEGORY = 'DOG';

--4.
SELECT MIN(PRICE)
 FROM ITEM;

--5.
SELECT FIRST_NAME, LAST_NAME
 FROM CUSTOMER
WHERE CREDIT_LIMIT >= 1000;

--6.
SELECT INVOICE_NUM
 FROM INVOICES
WHERE CUST_ID = 125
 AND INVOICE_DATE = '2021-11-15';

--7.
SELECT FIRST_NAME, LAST_NAME, CUST_ID
 FROM CUSTOMER
WHERE REP_ID IN (10, 15);

--8.
SELECT ITEM_ID, DESCRIPTION
 FROM ITEM
WHERE NOT CATEGORY = 'HOR';

--9.
SELECT ITEM_ID, DESCRIPTION, (ON_HAND * PRICE) AS ON_HAND_VALUE
 FROM ITEM
WHERE CATEGORY = 'CAT';

--10.
SELECT ITEM_ID, DESCRIPTION, (ON_HAND * PRICE) AS ON_HAND_VALUE
 FROM ITEM
WHERE (ON_HAND * PRICE) >=1500;

--11.
SELECT ITEM_ID, DESCRIPTION
 FROM ITEM
WHERE CATEGORY IN ('FSH', 'BRD');

--12.
SELECT CUST_ID, FIRST_NAME, LAST_NAME
 FROM CUSTOMER
WHERE FIRST_NAME LIKE 's%';

--13.
SELECT REP_ID, SUM(BALANCE)
 FROM CUSTOMER
GROUP BY REP_ID
 HAVING SUM(BALANCE) > 150
 ORDER BY REP_ID;


--Student Housing Database

-- 14.
SELECT OWNER_NUM, LAST_NAME, FIRST_NAME
 FROM OWNER

 --15.
SELECT FIRST_NAME, LAST_NAME
 FROM OWNER
WHERE CITY = 'Seattle';

--16.
SELECT PROPERTY_ID
 FROM PROPERTY
WHERE SQR_FT < 1600;

--17.
SELECT COUNT(*) AS TWO_FLOOR_PROPERTIES
 FROM PROPERTY
WHERE FLOORS = 2;

--18.
SELECT COUNT(*) AS OUT_OF_STATE_OWNERS
 FROM OWNER
WHERE STATE <> 'WA';

--19.
SELECT AVG(MONTHLY_RENT) AS AVG_3BR_RENT
 FROM PROPERTY
WHERE BDRMS = 3;

--20.
INSERT INTO SERVICE_CATEGORY 
 (CATEGORY_NUM, CATEGORY_DESCRIPTION)
 VALUES (
	(SELECT MAX(CATEGORY_NUM) + 1 FROM SERVICE_CATEGORY), 'Cleaning' );

--21.
INSERT INTO SERVICE_REQUEST (
  SERVICE_ID,
  PROPERTY_ID, 
  CATEGORY_NUM,
  OFFICE_NUM,
  DESCRIPTION,
  STATUS,
  EST_HOURS,
  SPENT_HOURS
)
VALUES (
  13,
  7,
  (SELECT CATEGORY_NUM FROM SERVICE_CATEGORY WHERE CATEGORY_DESCRIPTION = 'Cleaning'),
  2,
  'Office 2, clean property 7 top to bottom',
  'Open',
  4,
  0  
);

--22.
UPDATE SERVICE_REQUEST
 SET
  EST_HOURS = 8,
  SPENT_HOURS = 2
 WHERE SERVICE_ID = 10;

--23.
UPDATE SERVICE_CATEGORY
 SET CATEGORY_DESCRIPTION = 'Cleaning and Sanitizing'
WHERE CATEGORY_DESCRIPTION = 'Cleaning'; 

--24.
DELETE 
 FROM SERVICE_REQUEST
WHERE PROPERTY_ID = 7;

--25.
DELETE
 FROM SERVICE_CATEGORY
WHERE CATEGORY_DESCRIPTION = 'Cleaning and Sanitizing';

